chore: debug

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -36,6 +36,23 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v4
 
+    - name: Debug Secrets
+      run: |
+        echo "Checking TS_OAUTH_CLIENT_ID"
+        if [ -z "${{ secrets.TS_OAUTH_CLIENT_ID }}" ]; then
+          echo "::error::TS_OAUTH_CLIENT_ID is empty"
+          exit 1
+        else
+          echo "TS_OAUTH_CLIENT_ID is set"
+        fi
+        echo "Checking TS_OAUTH_SECRET"
+        if [ -z "${{ secrets.TS_OAUTH_SECRET }}" ]; then
+          echo "::error::TS_OAUTH_SECRET is empty"
+          exit 1
+        else
+          echo "TS_OAUTH_SECRET is set"
+        fi
+
     - name: Tailscale
       uses: tailscale/github-action@v3
       with:
