feat: various fixes and workflow update to deploy

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -10,24 +10,9 @@ on:
 
 jobs:
   deploy:
-    runs-on: ubuntu-24.04-arm
+    runs-on: ubuntu-24.04
 
     steps:
-      # - name: Free Disk Space (Ubuntu)
-      #   uses: jlumbroso/free-disk-space@main
-      #   with:
-      #     # this might remove tools that are actually needed,
-      #     # if set to "true" but frees about 6 GB
-      #     tool-cache: true
-      #     # all of these default to true, but feel free to set to
-      #     # "false" if necessary for your workflow
-      #     android: true
-      #     dotnet: true
-      #     haskell: true
-      #     large-packages: true
-      #     docker-images: true
-      #     swap-storage: true
-      #
       - uses: wimpysworld/nothing-but-nix@main
         with:
           hatchet-protocol: "holster"
@@ -37,38 +22,57 @@ jobs:
           extra-conf: |
             lazy-trees = true
 
-      # - name: Set up FlakeHub Cache and local cache
-      #   uses: DeterminateSystems/flakehub-cache-action@main
-
       - name: Checkout repository
         uses: actions/checkout@main
         with:
           fetch-depth: 0
 
-      # - name: Tailscale
-      #   uses: tailscale/github-action@main
-      #   with:
-      #     oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
-      #     oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
-      #     tags: tag:ci
+      - name: Tailscale
+        uses: tailscale/github-action@main
+        with:
+          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
+          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
+          tags: tag:ci
 
       - uses: cachix/cachix-action@v15
         with:
           name: volodiapg
           authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
 
-      # - name: Install SSH key
-      #   uses: shimataro/ssh-key-action@v2
-      #   with:
-      #     key: ${{ secrets.SSH_KEY }}
-      #     known_hosts: ${{ secrets.KNOWN_HOSTS }}
-      #     if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
+      - name: Install SSH key
+        uses: shimataro/ssh-key-action@v2
+        with:
+          key: ${{ secrets.SSH_KEY }}
+          known_hosts: ${{ secrets.KNOWN_HOSTS }}
+          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
 
-      # - name: Build and deploy
-      #   run: |
-      #     set -euxo pipefail
-      #     nix run .#deploy-rs -- --targets .#dell,.#home-server
-      #
+      - name: Build and deploy
+        run: |
+          set -euxo pipefail
+          nix run .#deploy-rs -- --skip-flake-checks --targets .#home-server
+
+  cache:
+    runs-on: ubuntu-24.04-arm
+
+    steps:
+      - uses: wimpysworld/nothing-but-nix@main
+        with:
+          hatchet-protocol: "holster"
+
+      - uses: DeterminateSystems/determinate-nix-action@v3
+        with:
+          extra-conf: |
+            lazy-trees = true
+
+      - name: Checkout repository
+        uses: actions/checkout@main
+        with:
+          fetch-depth: 0
+
+      - uses: cachix/cachix-action@v15
+        with:
+          name: volodiapg
+          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
 
       - name: Build to cache
         run: |
